-- 初始化主Bot记录到数据库
-- 用于修复主Bot在数据库中不存在导致的租户上下文查找失败问题

INSERT INTO bot_creations (
    telegram_id,
    bot_token,
    bot_username,
    bot_name,
    instance_id,
    instance_dir,
    db_path,
    env_path,
    status,
    super_admin_id,
    parent_bot_id,
    root_bot_id,
    tree_depth,
    core_version,
    ui_version,
    permission_version,
    created_at,
    started_at,
    stopped_at,
    updated_at,
    config_json,
    config_snapshot
) VALUES (
    8700502141,
    '8700502141:PLACEHOLDER_TOKEN',
    'main_bot',
    'Main Bot',
    'bot_8700502141',
    '/app/bot_instances/bot_8700502141',
    '/app/bot_instances/bot_8700502141/data.db',
    '/app/bot_instances/bot_8700502141/.env',
    'running',
    7862093562,
    NULL,
    'bot_8700502141',
    0,
    '1.0.0',
    '1.0.0',
    '1.0.0',
    NOW(),
    NOW(),
    NULL,
    NOW(),
    '{}',
    '{"enable_ai": false, "enable_auto_day_cut": true}'
) ON CONFLICT (instance_id) DO UPDATE SET
    telegram_id = EXCLUDED.telegram_id,
    bot_username = EXCLUDED.bot_username,
    status = EXCLUDED.status,
    super_admin_id = EXCLUDED.super_admin_id,
    updated_at = NOW();
